version: '3'
services:
    config:
        build:
            context: ./config-server
            dockerfile: Dockerfile
        ports:
            - '8888:8888'
    eureka:
        build:
            context: ./eureka-server
            dockerfile: Dockerfile
        ports:
            - '8761:8761'
        restart: on-failure
        depends_on:
            - config
        links:
            - config
    zuul:
        build:
            context: ./zuul-server
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        restart: on-failure
        depends_on:
            - config
            - eureka
        links:
            - config
            - eureka
#    suggestion:
#        build:
#            context: ./suggestion-server
#            dockerfile: Dockerfile
#        ports:
#            - '8081:8081'
#        restart: on-failure
#        depends_on:
#            - config
#            - eureka
#            - zuul
#        links:
#            - config
#            - eureka
#            - zuul

    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - 2181:2181

    kafka:
        image: wurstmeister/kafka:0.10.2.1
        ports:
            - "9092:9092"
        links:
            - zookeeper
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
            KAFKA_LISTENERS: "PLAINTEXT://:9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    kafka-rest:
        image: nodefluent/kafka-rest
        ports:
            - 8182:8182
        links:
            - kafka
            - zookeeper
        depends_on:
            - kafka
            - zookeeper
        environment:
            KAFKA_REST_DEBUG: "all"
            KAFKA_REST_HTTP_PORT: 8182
            KAFKA_REST_CONSUMER_METADATA_BROKER_LIST: "kafka:9092"
            KAFKA_REST_PRODUCER_METADATA_BROKER_LIST: "kafka:9092"

    kafka-topics-ui:
        image: landoop/kafka-topics-ui
        ports:
            - 8000:8000
        links:
            - kafka-rest
        depends_on:
            - kafka-rest
        environment:
            KAFKA_REST_PROXY_URL: "http://kafka-rest:8182"
            PROXY: "true"

#    jaimail-router:
#        build:
#            context: ./jaimail-router-server
#            dockerfile: Dockerfile
#        ports:
#            - '8082:8082'
#        restart: on-failure
#        depends_on:
#            - config
#            - eureka
#            - zuul
#            - kafka
#        links:
#            - config
#            - eureka
#            - zuul